- .github/workflows/update.yml
We have a flake for testing shellcheck, so let's keep that up-to-date :)
> update: init action using ourself

- README.md
- action.yml
Allow to run ci. Example: https://github.com/nix-community/nix-eval-jobs/pull/28
> allow to set different github token.

- README.md
- action.yml
Added functionality for changing the Commit Message, Title and Labels to be set on the PR to be created. Motivated by: [#5905](https://github.com/NixOS/nix/pull/5905)
Requires Nix >= 2.6
> Cosmetic Improvements

- README.md
- action.yml
Closes https://github.com/DeterminateSystems/update-flake-lock/issues/27.
* Seems to work fine: https://github.com/cole-h/update-flake-lock-test/runs/6117872227?check_suite_focus=true
> Expose the number of the opened PR

- README.md
Closes https://github.com/DeterminateSystems/update-flake-lock/issues/16.
> README: document an example that explicitly skips PRs

- action.yml
Makes it possible to customize the branch name.
> Expose option to configure branch for PR

- README.md
- action.yml
Implementing commit signing as requested in https://github.com/DeterminateSystems/update-flake-lock/issues/37
Still testing, that's why it's a draft PR
- With signed commits and custom PR body: https://github.com/edulix/update-flake-lock-test/pull/7
- No signature and default PR body: https://github.com/edulix/update-flake-lock-test-unsigned/pull/1
> adding support for gpg commit signing and custom pr body

- README.md
Otherwise, it could be interpreted as HTML tags and cause weird rendering.
> README: antiquote string with angled braces

- action.yml
Fixes https://github.com/DeterminateSystems/update-flake-lock/issues/40.
* https://github.com/cole-h/update-flake-lock-test/runs/7580884558?check_suite_focus=true
> Prevent template files from being committed

- README.md
- action.yml
> feat: allow using a subkey for GPG signing

- action.yml
> chore: bump `crazy-max/ghaction-import-gpg`

- action.yml
> allow to set base branch of pull request

- action.yml
> Bump `peter-evans/create-pull-request` to v5

- action.yml
Update `peter-evans/create-pull-request` to `v6` to address #94.
Tested [here](https://github.com/devusb/nix-config/actions/runs/8087962025).
> Update `peter-evans/create-pull-request` to v6

- action.yml
> Update DamianReeves/write-file-action to v1.3

- action.yml
> Update pedrolamas/handlebars-action to 2.4.0

- README.md
This PR updates the readme to use v4 of [https://github.com/actions/checkout?tab=readme-ov-file#checkout-v4](https://github.com/actions/checkout?tab=readme-ov-file#checkout-v4)
> Update README.md to use actions/checkout@v4

- action.yml
> Make strict mode input not required

- .eslintrc.json
- dist/index.js
- pnpm-lock.yaml
> Update detsys-ts for srv

- package.json
- pnpm-lock.yaml
> pnpm update, vitest

- .github/workflows/ci.yml
- .github/workflows/update.yml
- .github/workflows/validate.yml
- README.md
> Update to use our new nix action
